name=MicroBlue
version=1.3.0
author=SnappyXO
maintainer=A+ Mobile Solutions Inc
sentence=Arduino library to send messages between MicroBlue app and Arduino
paragraph=This is an Arduino library to send messages between MicroBlue app and Arduino Uno R3 and R4 boards, using an HM 10 Bluetooth module or the built-in BLE radio of the Uno R4 WiFi
category=Communication
url=https://github.com/snappyxo/microblue-arduino
architectures=*
includes=MicroBlue.h
depends=ArduinoBLE
